exclude_patterns:
- "__tests__/"
- "next.config.js"
- "**/node_modules/"
- "**/test/"
- "**/__tests__/"
- "**/tests/"
- "/jest.config/"
- "/**/__mocks__/"
- "scripts/"
- "cypress/"
version: "2"
checks:
  similar-code:
    config:
      threshold: 75
  identical-code:
    config:
      threshold: 75
  method-lines:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 25
