export const OPEN_MODAL = 'OPEN_MODAL';
export const OPEN_MODAL_SUCCESS = 'OPEN_MODAL_SUCCESS';
export const OPEN_MODAL_FAILURE = 'OPEN_MODAL_FAILURE';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CLOSE_MODAL_SUCCESS = 'CLOSE_MODAL_SUCCESS';
